tvseries4u/config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#welcome'
  get '/home', to: 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get '/signup', to: 'users#new'
  post '/signup',  to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user
  match 'movies/:id' => 'movies#destroy', :via => :delete, :as => :admin_destroy_movie
  match 'genders/:id' => 'genders#destroy', :via => :delete, :as => :admin_destroy_gender

  get 'visitante', to: 'visitor#action'

  get '/new_movie', to: 'movies#new'
  get '/movie_mail', to: 'movies#mail'
  get '/movie_download', to: 'movies#download'

  get '/new_gender', to: 'genders#new'

#  get '/season', to: 'seasons#show'

  get'/filtrar', to: 'functions#filtrar'
  get'/search', to: 'functions#search'

  get '/users/:id/signup_boy', to: 'users#new_boy', :as => :new_boy_creation
  get '/users/:id/boy_accounts', to: 'users#boy_index', :as => :boy_accounts
  post '/users/:id/signup_boy', to: 'users#create_cuenta_niño'

  get '/statistics', to: 'statistics#principal'
  get '/st_generales_path', to: 'statistics#generales'
  get '/st_usuario_path', to: 'statistics#usuario'
  get '/st_graficos_path', to: 'statistics#graficos'

  resources :users do
    member do
      get :following, :followers, :genders
    end
  end
  resources :users
  resources :seasons
  resources :movies do
    resources :comments
    resources :seasons
  end

  resources :seasons do
    resources :episodes
  end

  resources :episodes do
    member do
      put "like" => "episodes#vote"
    end
  end

  resources :genders
  resources :movies,          only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
#<!--  <% if current_user.id = movie.user_id %>
#  <span class="name"><%= link_to movie.name, movie, style: 'color:#2E9AFE;' %></span>
#  <% else %>
#  no es igual
#  <span class="name"><%= movie.name %></span>
#  <% end %>-->

tvseries4u/app/models/episode.rb
class Episode < ApplicationRecord
  acts_as_votable

  belongs_to :season
end

tvseries4u/app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController
	before_action :find_season
	before_action :find_episode, only: [:destroy, :vote]


	def index
		@episode = Episode.all
	end

	def new
		@episode = Season.episodes.new
	end

	def vote
		if !current_user.liked? @episode
			@episode.liked_by current_user
		elsif current_user.liked? @episode
			@episode.unliked_by current_user
		end
		redirect_to :back
	end

	def create
		@episode = @season.episodes.create(params[:episode])
		@episode.numero = @season.episodes.count
		@episode.user_id = current_user.id

		if @episode.save
			redirect_to request.referrer
		else
			render 'new'
		end
	end

	def show
		@episode = Episode.find(params[:id])
		#@season = Season.find_by(movie_id: params[:movie_id])
	end

	def destroy
		@episode.destroy
  		redirect_to request.referrer || root_url
	end

	private

		def find_episode
			@episode = Episode.find(params[:id])
		end

		def find_season
			@season = Season.find(params[:season_id])
		end
end

tvseries4u/app/helpers/episodes_helper.rb
module EpisodesHelper
end

tvseries4u/app/views/episodes/_episode.html.erb
<div class="jumbotron">
<center>
<%= link_to "Volver a "+ @movie.name, movie_path(id: @movie.id), align: :left %><br>
<b><%= "Capítulo Vistos"%></b><br>
<% @episodes.each do |episode| %>
  <%= "Capítulo "+episode.numero.to_s %>
  <%= link_to like_episode_path(id: episode.id, season_id: episode.season_id), class:"like-btn", method: :put, remote: :true do %>
  	<% if current_user.liked? episode %>
  		<span><i class="fa fa-eye fa-2x" aria-hidden="true" style="color:black" ></i></span>

    <% elsif !current_user.liked? episode %>
      <span><i class="fa fa-eye fa-2x" aria-hidden="true" style="color:grey"></i></span>
  	<% end %>
    <% end %>
  <br>
<% end %>
<br>
<% @last_episode = @episodes.order(:id).last %>
<% if @last_episode %>
	<% if current_user.id == @last_episode.user_id || current_user.admin? %>
	    <%= link_to "Borrar último episodio", [@last_episode.season, @last_episode], method: :delete %>
	<% end %>
<% end %>
<% if logged_in? %>
	<%= render 'episodes/form' %>
<% end %>
</center>
</div>

tvseries4u/app/views/episodes/_form.html.erb
<%= form_for([@season, @season.episodes.build(season_id:@season.id)]) do |f| %>
	<%= f.submit %>	
<% end %>  

tvseries4u/app/views/episodes/like.js.erb
<% if current_user.liked? episode %>
	$('.like-btn').addClass('liked');
  <% else %>
    $('.like-btn').removeClass('liked');	

<% end %>

tvseries4u/app/views/episodes/vote.js.erb
<% if current_user.liked? @episode %>
	$('.like-btn').addClass('liked');
  <% else %>
    $('.like-btn').removeClass('liked');	

<% end %>