tvseries4u/config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#welcome'
  get '/home', to: 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get '/signup', to: 'users#new'
  post '/signup',  to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user
  match 'movies/:id' => 'movies#destroy', :via => :delete, :as => :admin_destroy_movie
  match 'genders/:id' => 'genders#destroy', :via => :delete, :as => :admin_destroy_gender

  get 'visitante', to: 'visitor#action'

  get '/new_movie', to: 'movies#new'
  get '/movie_mail', to: 'movies#mail'
  get '/movie_download', to: 'movies#download'

  get '/new_gender', to: 'genders#new'

#  get '/season', to: 'seasons#show'

  get'/filtrar', to: 'functions#filtrar'
  get'/search', to: 'functions#search'

  get '/users/:id/signup_boy', to: 'users#new_boy', :as => :new_boy_creation
  get '/users/:id/boy_accounts', to: 'users#boy_index', :as => :boy_accounts
  post '/users/:id/signup_boy', to: 'users#create_cuenta_niño'

  get '/statistics', to: 'statistics#principal'
  get '/st_generales_path', to: 'statistics#generales'
  get '/st_usuario_path', to: 'statistics#usuario'
  get '/st_graficos_path', to: 'statistics#graficos'

  resources :users do
    member do
      get :following, :followers, :genders
    end
  end
  resources :users
  resources :seasons
  resources :movies do
    resources :comments
    resources :seasons
  end

  resources :seasons do
    resources :episodes
  end

  resources :episodes do
    member do
      put "like" => "episodes#vote"
    end
  end

  resources :genders
  resources :movies,          only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
#<!--  <% if current_user.id = movie.user_id %>
#  <span class="name"><%= link_to movie.name, movie, style: 'color:#2E9AFE;' %></span>
#  <% else %>
#  no es igual
#  <span class="name"><%= movie.name %></span>
#  <% end %>-->

tvseries4u/app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :logged_in?, only: [:create, :destroy]

  def new
    @movie = Movie.new
    if not current_user.admin?
      @genders= current_user.genders + Gender.where(:user_id => 1)
    else
      @genders= current_user.genders
    end
  end

  def create
    puts movie_params[:gender]
    @movie = current_user.movies.new(movie_params)

    if @movie.gender == "new"
      @gender=Gender.new
      @movie.gender=Gender.new
      render 'genders_path'
    else
      if @movie.save
        flash[:success] = "Serie agregada!"+@movie.gender
        redirect_to home_url
      else
        @feed_items = []
        render 'static_pages/home'
      end
    end
  end

  def mail
    NotifierMailer.send_list(current_user).deliver
    flash[:success] = "Lista de series enviada a "+current_user.email
    redirect_to home_url
  end

  def download
    @user=current_user
    send_data generate_pdf(@user),:type => 'application/pdf',:disposition => "attachment; filename=lista_"+@user.name+".pdf"
  end

  def show
    @movie=Movie.all.find(params[:id])
    @comments=Comment.where(movie_id: @movie).order("created_at DESC")
    @seasons=Season.where(movie_id: @movie).order("created_at ASC")
#   @movie = current_user.movies.find(params[:id])
  end

  def season
    @movie=Movie.all.find(params[:id])
    @season=@movie.season.find(params[:id])
  end

  def destroy
    @movie= Movie.find(params[:id]).destroy
    if @movie.destroy
      flash[:success] = "Serie eliminada exitosamente"
      redirect_to request.referrer || root_url
    else
      flash[:error] = "No se pudo borrar el usuario"
      redirect_to request.referrer || root_url
    end
  end

  private

    def movie_params
      params.require(:movie).permit(:name, :gender, :description, :year, :director, :language)
    end

    def correct_user
      @movie = current_user.movies.find_by(id: params[:id])
      redirect_to root_url if @movie.nil?
    end

    def generate_pdf(user)
      Prawn::Document.new do
        if user.id == 1
          @movies=Movie.all
        else
          @movies=Movie.where(user_id: user.id).or(Movie.where(user_id: 1))
        end
        font "Helvetica", style: :bold
        font_size 20
        text "Lista de series de "+user.name, :align => :center
        text " "
        @movies.each do |movie|
          font "Helvetica", style: :italic
          font_size 15
          text ""+movie.name, :align => :center
          text " "
          font "Helvetica"
          font_size 10
          if movie.gender.present?
            text "Género: #{movie.gender}"
          end
          if movie.description.present?
            text "Descripción: "+movie.description
          end
          text " "
          text " "
        end
      end.render
  end

end

tvseries4u/app/views/movies/_movie.html.erb
<li id="<%= movie.id %>">
  <center><h4><b><span class="glyphicon glyphicon-play">
  <%= link_to movie.name,  movie, style: 'color:#2E9AFE;' %>
  </span></h4></b>
  <% if movie.gender.present? %><br>
    <span class="gender"><b>Género: </b><%= movie.gender %></span>
  <% end %>
  <% if movie.description.present? %><br>
    <span class="description"><b>Descripción: </b><%= movie.description %></span>
  <% end %>
  <% if movie.director.present? %><br>
    <span class="description"><b>Año: </b><%= movie.director %></span>
  <% end %>
  <% if movie.language.present? %><br>
    <span class="description"><b>Idioma: </b><%= movie.language %></span>
  <% end %>
  <% if movie.year.present? %><br>
    <span class="description"><b>Año: </b><%= movie.year %></span>
  <% end %>
  <span class="timestamp"><br>
    Posted <%= time_ago_in_words(movie.created_at) %> ago.
    <% if current_user.present? && (current_user.id == movie.user_id || current_user.admin?)%>
      <%= link_to "delete", admin_destroy_movie_path(movie),
       method: :delete, data: { confirm: "Estás seguro que quieres eliminar la serie #{movie.name} de #{movie.user.name}?" } %>
    <% end %>
  </span></center>
</li><br>

tvseries4u/app/views/movies/get_content.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
  </head>
  <body>
    <h1>Lista de series de <%= @user.name %></h1>
    <% @movies.each do |movie|  %>
    <div class="row">
        <div class="col-md-15">
          <center><h3> <%= movie.name %> </h3></center>
          <% if movie.gender.present? %>
            <h5> Género: <%= movie.gender %></h5>
          <% end %>
          <% if movie.description.present? %>
            <h5>Descripción: <%= movie.description %></h5>
          <% end %>
          <% if movie.year.present? %>
            <h5>Year: <%= movie.year.to_s %></h5>
          <% end %>
          <br>
    </div>
  </div>
    <% end %>
  </body>
</html>

tvseries4u/app/views/movies/new.html.erb
<h1>Añadir nueva serie</h1>
<div clas="container">
  <div class="jumbotron">
    <%= form_for(@movie) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <%= f.label :nombre %>
    <%= f.text_field :name, placeholder: "Ingresa nombre de nueva serie .." %>
    <%= f.label :"selecciona género" %>
    <%= f.select(:gender, @genders.collect {|p| [ p.name ] } + [ [ 'Crear nuevo género', 'new' ] ], {:include_blank => true}) %>
    <%= f.label :descripción %>
    <%= f.text_area :description, placeholder: "Ingresa descripción de serie" %>
    <%= f.label :director %>
    <%= f.text_field :director, placeholder: "Ingresa el director" %>
    <%= f.label :idioma %>
    <%= f.text_field :language, placeholder: "Ingresa el idioma" %>
    <%= f.label :año %>
    <%= f.number_field :year, placeholder: "Ingresa año" %>
    <%= f.submit "Añadir", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

tvseries4u/app/views/movies/show.html.erb
<% provide(:title, @movie.name) %>
<h1><%=@movie.name%></h1>
<div class="jumbotron">
<div class="row">
    <% if @movie.gender.present? %>
    <span class="gender"><b>Género:</b> <%= @movie.gender %></span><br>
    <% end %>
    <% if @movie.description.present? %>
    <span class="description"><b>Descripción:</b> <%= @movie.description %></span><br>
    <% end %>
    <% if @movie.director.present? %>
    <span class="description"><b>Año:</b> <%= @movie.director %></span><br>
    <% end %>
    <% if @movie.language.present? %>
    <span class="description"><b>Idioma:</b> <%= @movie.language %></span><br>
    <% end %>
    <% if @movie.year.present? %>
    <span class="description"><b>Año:</b> <%= @movie.year %></span><br>
    <% end %>
    <b>Temporadas: </b><%= @movie.seasons.count %></span><br>
    <% @cantidad_capitulos = 0 %>
    <% @cantidad_capitulos_vistos = 0 %>
    <% @movie.seasons.each do |season| %>
    	<% @cantidad_capitulos += season.episodes.count %>
    	<% season.episodes.each do |episode| %>
    		<% if current_user.liked? episode %>
    			<% @cantidad_capitulos_vistos += 1 %>
    		<% end %>
    	<% end %>
    <% end %>
    <b>Capítulos: </b><%= @cantidad_capitulos %><b> Vistos: </b><%= @cantidad_capitulos_vistos %>
  </div>
</br>
<div class="row">
  <%= render 'seasons/season' %>
  <%= render 'comments/comment' %>
</div>
</div>