tvseries4u/config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#welcome'
  get '/home', to: 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get '/signup', to: 'users#new'
  post '/signup',  to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user
  match 'movies/:id' => 'movies#destroy', :via => :delete, :as => :admin_destroy_movie
  match 'genders/:id' => 'genders#destroy', :via => :delete, :as => :admin_destroy_gender

  get 'visitante', to: 'visitor#action'

  get '/new_movie', to: 'movies#new'
  get '/movie_mail', to: 'movies#mail'
  get '/movie_download', to: 'movies#download'

  get '/new_gender', to: 'genders#new'

#  get '/season', to: 'seasons#show'

  get'/filtrar', to: 'functions#filtrar'
  get'/search', to: 'functions#search'

  get '/users/:id/signup_boy', to: 'users#new_boy', :as => :new_boy_creation
  get '/users/:id/boy_accounts', to: 'users#boy_index', :as => :boy_accounts
  post '/users/:id/signup_boy', to: 'users#create_cuenta_niño'

  get '/statistics', to: 'statistics#principal'
  get '/st_generales_path', to: 'statistics#generales'
  get '/st_usuario_path', to: 'statistics#usuario'
  get '/st_graficos_path', to: 'statistics#graficos'

  resources :users do
    member do
      get :following, :followers, :genders
    end
  end
  resources :users
  resources :seasons
  resources :movies do
    resources :comments
    resources :seasons
  end

  resources :seasons do
    resources :episodes
  end

  resources :episodes do
    member do
      put "like" => "episodes#vote"
    end
  end

  resources :genders
  resources :movies,          only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
#<!--  <% if current_user.id = movie.user_id %>
#  <span class="name"><%= link_to movie.name, movie, style: 'color:#2E9AFE;' %></span>
#  <% else %>
#  no es igual
#  <span class="name"><%= movie.name %></span>
#  <% end %>-->

tvseries4u/app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    TVSeries4u 2017 - Ingeniería de Software
    , <a href="https://github.com/IIC2143-2017/Grupo13">GitHub repository</a>
    by Grupo 13</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", about_path, style: 'color:#FFFFFF;' %></li>
      <li><%= link_to "Contact", contact_path, style: 'color:#FFFFFF;' %></li>
    </ul>
  </nav>
</footer>

tvseries4u/app/views/layouts/_header.html.erb
<% if logged_in? %>
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to image_tag("logo2.png", :width => 100, :height => 40), root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", home_path %></li>
        <li><%= link_to "Búsqueda", '#' %></li>
        <li><%= link_to "Ayuda", help_path %></li>
        <% if logged_in? %>
          <% if current_user.admin? %>
          <li><%= link_to "Usuarios", users_path %></li>
          <li><%= link_to "Estadísticas", statistics_path %></li>
          <% end %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Cuenta <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Perfil", current_user %></li>
              <li><%= link_to "Configuración", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Salir", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Ingresar", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>
<% else %>
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to image_tag("logo2.png", :width => 100, :height => 40), root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Visitante", visitante_path %></li>
        <li><%= link_to "Ingresar", login_path %></li>
      </ul>
    </nav>
  </div>
</header>

<% end %>

tvseries4u/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TVSeries4u</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
      <div class="container">
        <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
        <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </div>
  </body>
</html>